[package]
name = "dev-tracker-core"
description = "Core data persistence for dev-tracker"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono = "0.4.26"
rusqlite = { version = "0.29.0", features = ["bundled", "chrono"] }
