[workspace]
members = [
	"dev-tracker-core",
]

[workspace.package]
authors = ["Keith Sharp <kms@passback.co.uk"]
description = "Tracking project development progress"
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
